package com.asknilesh.dreamdate.navigation

enum class DreamDateScreens {
  INTRO_SCREEN,
  LOGIN_SCREEN,
  ENTER_PHONE_NUMBER_SCREEN,
  VERIFY_OTP_SCREEN,
  GENDER_SELECTION_SCREEN,
  SELECT_USER_NAME_SCREEN,
  HOME_SCREEN,
  DASHBOARD_SCREEN,
  EXPLORE_SCREEN,
  SHORTS_SCREEN,
  MESSAGES_SCREEN,
  PROFILE_SCREEN,
  NOTIFICATION_SCREEN,
  ADD_NEW_POST_SCREEN,
  USER_PROFILE_SCREEN,
  USER_FOLLOWERS_SCREEN,
  CHAT_SCREEN,
  LIVE_SCREEN;
}